### ISSUE TITLE
Database error when running `php artisan migrate`

### ISSUE THREAD

**Issue by zackkatz** [code-debug228/HostetskiGPT#15] opened 2023-06-06 18:21 UTC
It appears there should be a column with a primary key in the table.

> SQLSTATE[HY000]: General error: 3750 Unable to create or change a table without a primary key, when the system vari
  able 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message.
   Note that tables without a primary key can cause performance problems in row-based replication, so please consult
  your DBA before changing this setting. (SQL: create table `hostetskigpt` (`mailbox_id` int not null, `enabled` tiny
  int(1) not null, `api_key` varchar(191) not null, `token_limit` int not null, `start_message` varchar(191) not null
  , `model` varchar(191) not null) default character set utf8mb4 collate utf8mb4_unicode_ci)

**Comment by AliakseyM** [comment] 2023-06-06 22:15
Thank you for your message. This error is caused by the strict mode of MySQL. To resolve it, you can disable strict mode in MySQL or wait for a fix to be released by tomorrow.

**Comment by code-debug228** [comment] 2023-06-07 19:54
Now the error should be fixed, download updated module code and try to run the migration again.

**Comment by zackkatz** [comment] 2023-06-07 20:04
Thank you, @code-debug228 !

**Closed** 2023-06-07 20:19 UTC
